---
- hosts: webserver
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start apache servers
      service:
        name: apache2
        state: started
  
  