apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: nodeappds
spec:
  selector: 
    matchLabels: 
      app: nodeapp
  template:
    metadata: 
       name: node-app-pod
       labels:
          app: nodeapp
    spec:
      containers:
      - image: dockerhandson/nodeappmss:1
        name: nodeappcontainer
        ports:
        - containerPort: 9981
---
apiVersion: v1 
kind: Service
metadata:
   name: nodeappservice
spec: 
  selector:
     app: nodeapp
  ports:
  - port: 80
    targetport: 9981
  type: ClusterIP
    

