apiVersion: v1
kind: Pod
metadata:
   name: demo-webapp
   labels:
     app: webapp
spec:
  containers:
  - name: demo-webapp
    image: bindunuthalapati59/harsha:24.04
    ports:
    - containerPort: 80
    