apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
  labels:
    app: maven-webapp
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-webapp
  template:
    metadata:
      labels:
        app: maven-webapp
        environment: production
    spec:
      containers:
      - name: maven-webapp-container
        image: dockerhandson/maven-web-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: maven-webapp-service
  labels:
    app: maven-webapp
    environment: production
spec:
  selector:
    app: maven-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP