apiVersion: v1
kind: Pod
metadata: 
   name: Java-webapp
   labels:
     app: webapp
spec:
  containers:
  - name: maven
    image: dockerhandson/java-webapp
    ports:
    - containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
   name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetport: 8080
  type: ClusterIP