apiVersion: v1
kind: Pod
metadata: 
  name: harsha-pod
  namespace: bindu
  labels: 
    app: nginx
spec: 
  containers: 
  - name: nginx-container
    image: nginx
    ports: 
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
   name: nginxservice 
   namespace: bindu
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetport: 80
  type: ClusterIP
     

       