apiVersion: v1
kind: ReplicationController
metadata:
   name: java-webapp-rc
spec:
  replicas: 2
  selector: 
     app: webapp
  template: 
     metadata:
        name: java-webapp-pod
        labels:
          app: webapp
     spec: 
       containers:
       - name: java-webapp-container
         image: dockerhandson/java-web-app
         ports:
         - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
   name: webapp-service
spec:
  selector:
     app: webapp
     ports:
     - port: 80
       targetport: 8080
  type: ClusterIP