---
- name: template
  hosts: 192.168.56.15
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start service
      service:
         name: apache2
         state: started
    - name: copy files
      template:
         src: index.html
         dest: /var/www/html/index.html